development: &default
  city: Brașov
  support_email: bugetareparticipativa@brasovcity.ro
  financed_domains:
    bg_image: Brașov_background.png
    cards:
    - image: "orasul mobil.png"
      i18n: orasul_mobil
    - image: "orasul verde.png"
      i18n: orasul_verde
    - image: "Orasul relaxat.png"
      i18n: orasul_relaxat
    - image: "orasul comunitatilor.png"
      i18n: orasul_comunitatilor
  custom_pages:
    regulament:
      bgcolor: '#F68E21'
      color: '#fff'
    evaluarea-proiectelor:
      bgcolor: '#E02148'
      color: '#fff'
    calendar:
      bgcolor: '#66AD30'
      color: '#fff'
    faq:
      bgcolor: '#9A238E'
      color: '#fff'
    contact:
      bgcolor: '#5FC9AD'
      color: '#fff'
    despre-bugetare-participativa:
      bgcolor: '#1A4D9C'
      color: '#fff'
    terms-and-conditions:
      bgcolor: '#1A4D9C'
      color: '#fff'
    privacy-policy:
      bgcolor: '#1A4D9C'
      color: '#fff'
    news:
      bgcolor: '#9cc029'
      color: '#fff'
    rezultate:
      bgcolor: '#FEC20B'
      color: '#fff'
  investments_heading_icons:
    heading_id_2: 'custom_pages/orasul mobil_pg.png'
    heading_id_4: 'custom_pages/orasul verde_pg.png'
    heading_id_5: 'custom_pages/orasul comunitatilor_pg.png'
    heading_id_6: 'custom_pages/Orasul relaxat_pg.png'

staging:
  << : *default

production:
  << : *default
